create table bio_hab_metric_swap_stewards
(data_source_id                 number
,data_source                    varchar2(8 char)
,station_id                     number
,site_id                        varchar2(4000 char)
,organization                   varchar2(4000 char)
,site_type                      varchar2(4000 char)
,huc                            varchar2(4000 char)
,governmental_unit_code         varchar2(4000 char)
,index_identifier               varchar2(4000 char)
,index_type_identifier          varchar2(4000 char)
,index_type_context             varchar2(4000 char)
,index_type_name                varchar2(4000 char)
,resource_title_name            varchar2(4000 char)
,resource_creator_name          varchar2(4000 char)
,resource_subject_text          varchar2(4000 char)
,resource_publisher_name        varchar2(4000 char)
,resource_date                  varchar2(4000 char)
,resource_identifier            varchar2(4000 char)
,index_type_scale_text          varchar2(4000 char)
,index_score_numeric            varchar2(4000 char)
,index_qualifier_code           varchar2(4000 char)
,index_comment                  varchar2(4000 char)
,index_calculated_date          varchar2(4000 char)
,huc_2                          generated always as (case when length(huc) > 1 then substr(huc,1,2) else null end)
,huc_4                          generated always as (case when length(huc) > 3 then substr(huc,1,4) else null end)
,huc_6                          generated always as (case when length(huc) > 5 then substr(huc,1,6) else null end)
,huc_8                          generated always as (case when length(huc) > 7 then substr(huc,1,8) else null end)
,huc_10                         generated always as (case when length(huc) > 9 then substr(huc,1,10) else null end)
,huc_12                         generated always as (case when length(huc) = 12 then substr(huc,1,12) else null end)
,country_code                   generated always as (regexp_substr(governmental_unit_code, '[^:]+'))
,state_code                     generated always as (regexp_substr(governmental_unit_code, '[^:]+:[^:]+'))
,county_code                    generated always as (regexp_substr(governmental_unit_code, '[^:]+:[^:]+:[^:]+'))
) parallel 4 compress pctfree 0 nologging cache;
