create table if not exists ${WQP_SCHEMA_NAME}.web_service_log
(web_service_log_id             integer             primary key generated by default as identity
,request_timestamp_utc          timestamp(6)        default (now() at time zone 'UTC')
,head_sent_utc                  timestamp(6)
,first_row_sent_utc             timestamp(6)
,request_completed_utc          timestamp(6)
,origin                         text                not null
,call_type                      text                not null
,endpoint                       text                not null
,total_rows_expected            integer
,data_store_counts              jsonb
,http_status_code               text
,post_data                      jsonb
,user_agent                     text
,download_details               jsonb
)
;
