create table states
(state                          varchar2(26 char)
,state_abrv                     varchar2(2 char)
,fipsst                         varchar2(2 char)
,totpop                         number
,pctsmpld                       number
,landsqmi                       number
,poppsqmi                       number
,female                         number
,rural                          number
,onfarms                        number
,infamily                       number
,alone                          number
,groupqtr                       number
,popinhhs                       number
,pctfemal                       number
,pctgq                          number
,white                          number
,black                          number
,asianpi                        number
,amindian                       number
,hispanic                       number
,pctwhite                       number
,pctblack                       number
,pctasian                       number
,pctamind                       number
,pcthisp                        number
,pct0_4                         number
,pct5_9                         number
,pct10_13                       number
,pct14_17                       number
,pct18_24                       number
,pct25_34                       number
,pct35_44                       number
,pct45_54                       number
,pct55_59                       number
,pct60_64                       number
,pct65_74                       number
,pct75_84                       number
,pct85_up                       number
,pct0_19                        number
,pct20_39                       number
,pct40_64                       number
,pct65_up                       number
,age0_4                         number
,age5_9                         number
,age10_13                       number
,age14_17                       number
,age18_24                       number
,age25_34                       number
,age35_44                       number
,age45_54                       number
,age55_59                       number
,age60_64                       number
,age65_74                       number
,age75_84                       number
,age85_up                       number
,age0_19                        number
,age20_39                       number
,age40_64                       number
,age65_up                       number
,age0_17                        number
,age18_44                       number
,age45_64                       number
,medage                         number
,tothhs                         number
,avghhsz                        number
,hhs1ov65                       number
,hhs1                           number
,hhs2                           number
,hhs3_4                         number
,hhs5_up                        number
,pcthhs1                        number
,pcthhs2                        number
,pcthhs3_                       number
,pcthhs5_                       number
,families                       number
,mcfams                         number
,mcwchild                       number
,femhead                        number
,femheadc                       number
,nonfhhs                        number
,pctfamhh                       number
,pctmcfam                       number
,pctmcwch                       number
,pctfemhe                       number
,pctfemhc                       number
,pctnfhhs                       number
,hhi0_10                        number
,hhi10_15                       number
,hhi15_25                       number
,hhi25_35                       number
,hhi35_50                       number
,hhi50_75                       number
,hhi75_99                       number
,hhi100up                       number
,phi0_10                        number
,phi10_15                       number
,phi15_25                       number
,phi25_35                       number
,phi35_50                       number
,phi50_75                       number
,phi75_99                       number
,phi100up                       number
,phi0_15                        number
,phi0_25                        number
,phi0_35                        number
,phi0_50                        number
,phi0_75                        number
,phi0_99                        number
,medhhinc                       number
,avghhinc                       number
,geom                           mdsys.sdo_geometry
);
