#!/bin/bash

echo Building base container...
docker build -f ../Dockerfile -t wqp_db_base --build-arg LIQUIBASE_VERSION=$LIQUIBASE_VERSION --build-arg A_JDBC_JAR=$JDBC_JAR .

echo Building target container...
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME-$SOURCE_COMMIT .
